### PR TITLE
Feature: hide_dpdjs and hide_dashboard in config

### PR DESCRIPTION
**Pull request by ipepe**
Added new feature. You can now specify in config to hide /dashboard/ from public
or dpd.js file (and dashboard because it works based on dpd.js file)
from public.

### CODE REVIEW

**Comment by ipepe** [comment]
I need to fix tests. Sorry for delay ;)

**Comment by andreialecu** [comment]
Hey, thanks for adding this, it was needed. Please also add a test for it.

**Comment by ipepe** [comment]
Do You have an idea what a test case should look like?

**Comment by ipepe** [comment]
I fixed tests, we probably need to add usage to readme/docs. In short. to server options add:
```javascript
server.options.hide_dpdjs = true; // this hides dashboard also because dashboard uses dpd.js and it would be unusable
//or
server.options.hide_dashboard = true;
```

I also have a problem running mocha test, can anyone help me solve it? Should I create issue? Output here:
```bash

  1) "before all" hook
  2) "after all" hook

  0 passing (2s)
  2 failing

  1)  "before all" hook:
     Error
    at Object
  <anonymous> (/Users/patrykptasinski/GitHub/deployd/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:42:24)
      at Module._compile (module.js:460:26)
      at Object.Module._extensions..js (module.js:478:10)
      at Module.load (module.js:355:32)
      at Function.Module._load (module.js:310:12)
      at Module.require (module.js:365:17)
      at require (module.js:384:17)
      at Object.<anonymous> (/Users/patrykptasinski/GitHub/deployd/node_modules/mongodb/node_modules/mongodb-core/index.js:2:17)
      at Module._compile (module.js:460:26)
      at Object.Module._extensions..js (module.js:478:10)
      at Module.load (module.js:355:32)
      at Function.Module._load (module.js:310:12)
      at Module.require (module.js:365:17)
      at require (module.js:384:17)
      at Object.<anonymous> (/Users/patrykptasinski/GitHub/deployd/node_modules/mongodb/index.js:2:12)
      at Module._compile (module.js:460:26)
      at Object.Module._extensions..js (module.js:478:10)
      at Module.load (module.js:355:32)
      at Function.Module._load (module.js:310:12)
      at Module.require (module.js:365:17)
      at require (module.js:384:17)
      at Object.<anonymous> (/Users/patrykptasinski/GitHub/deployd/lib/db.js:4:15)
      at Module._compile (module.js:460:26)
      at Object.Module._extensions..js (module.js:478:10)
      at Module.load (module.js:355:32)
      at Function.Module._load (module.js:310:12)
      at Module.require (module.js:365:17)
      at require (module.js:384:17)
      at Object.<anonymous> (/Users/patrykptasinski/GitHub/deployd/lib/router.js:1:72)
      at Module._compile (module.js:460:26)
      at Object.Module._extensions..js (module.js:478:10)
      at Module.load (module.js:355:32)
      at Function.Module._load (module.js:310:12)
      at Module.require (module.js:365:17)
      at require (module.js:384:17)
      at Object.<anonymous> (/Users/patrykptasinski/GitHub/deployd/lib/attach.js:7:14)
      at Module._compile (module.js:460:26)
      at Object.Module._extensions..js (module.js:478:10)
      at Module.load (module.js:355:32)
      at Object.load (/Users/patrykptasinski/GitHub/deployd/node_modules/rewire/lib/moduleEnv.js:19:18)
      at internalRewire (/Users/patrykptasinski/GitHub/deployd/node_modules/rewire/lib/rewire.js:50:15)
      at rewire (/Users/patrykptasinski/GitHub/deployd/node_modules/rewire/lib/index.js:11:12)
      at Object.<anonymous> (/Users/patrykptasinski/GitHub/deployd/test/attach.unit.js:2:12)
      at Module._compile (module.js:460:26)
      at Object.Module._extensions..js (module.js:478:10)
      at Module.load (module.js:355:32)
      at Function.Module._load (module.js:310:12)
      at Module.require (module.js:365:17)
      at require (module.js:384:17)
      at /usr/local/lib/node_modules/mocha/lib/mocha.js:187:27
      at Array.forEach (native)
      at Mocha.loadFiles (/usr/local/lib/node_modules/mocha/lib/mocha.js:184:14)
      at Mocha.run (/usr/local/lib/node_modules/mocha/lib/mocha.js:405:31)
      at Object.<anonymous> (/usr/local/lib/node_modules/mocha/bin/_mocha:405:16)
      at Module._compile (module.js:460:26)
      at Object.Module._extensions..js (module.js:478:10)
      at Module.load (module.js:355:32)
      at Function.Module._load (module.js:310:12)
      at Function.Module.runMain (module.js:501:10)
      at startup (node.js:129:16)
      at node.js:814:3

  2)  "after all" hook:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at null.<anonymous> (/usr/local/lib/node_modules/mocha/lib/runnable.js:170:19)
      at Timer.listOnTimeout (timers.js:110:15)
```

**Comment by andreialecu** [comment]
Looks great @ipepe . Regarding your local test issue, the tests require a local mongodb instance running. They won't start an instance like `dpd` does, so you will need to start a `mongod` fork yourself if you don't have one.

**Comment by andreialecu** [comment]
One minor nitpick: could you restore spacing in the lines not affected by this feature? Your code editor seems to have changed a lot of spacing in other places. 

What I usually do is before committing - I look at the generated diff for each file and I can revert any places I didn't intent to change.

**Comment by ipepe** [comment]
But that's how it should be. No excessive characters and it's properly formatted

**Comment by andreialecu** [comment]
The extra spaces are so that declarations align underneath each other properly, it's a convention in the entire deployd code base. Not something I personally chosen but I think we should keep consistency
.
```javascript
var fs = require('fs')
, path = require('path')
, _loadTypes = require('./type-loader')
```

vs
```javascript
var fs = require('fs')
    , path = require('path')
    , _loadTypes = require('./type-loader')
```

**Comment by ipepe** [comment]
Better now?

**Comment by andreialecu** [comment]
Yes. Thank you.

**Comment by ipepe** [comment]
No big problem ;) I will try to watch out for variables spacing to prevent creating two formatting conventions

**Comment by andreialecu** [comment]
@ipepe Thanks for your contribution!
Landed as https://github.com/deployd/deployd/commit/a9328882bb48f0e2e5a793df8f38037dcd41eb41

**Comment by ipepe** [comment]
I'm glad You like it. I will try to add more and more to deployd project. I am big fan. This feature will be avaible as version 0.9.0?

**Comment by NicolasRitouet** [comment]
@ipepe since this is not a breaking change, it'll be available in a few days in the 0.8.3.

**Comment by NicolasRitouet** [comment]
Btw, @ipepe it would be awesome if you could send us a PR to add some documentation:
https://github.com/deployd/docs/issues/59

**Pull request closed without merging**
