### PR TITLE
Package dep updates

### PR DESCRIPTION
**Pull request by Kvarkas**
this solve issue with update for Windows users from 0.8.0 to 0.8.4

### CODE REVIEW

**Comment by andreialecu** [comment]
Looks like the tests are failing.

**Comment by Kvarkas** [comment]
Could you please provide more information that exactly are failing?

**Comment by ericfong** [comment]
Look like a timeout thing
https://travis-ci.org/deployd/deployd/jobs/70982329

**Comment by NicolasRitouet** [comment]
Apparently, this test is failing:
https://github.com/deployd/deployd/blob/4960d07fbade755470ee6d7ff29b9ccc7645c941/test-app/public/test/collection.test.js#L413
Don't know why though...
I'll try to investigate on this later.

**Pull request closed without merging**
