### PR TITLE
fix(internal-resource): handle errors in type events

### PR DESCRIPTION
**Pull request by Maddis1337**
The events used in lib/internal-resource previously ignored any errors that might have occured in the event, because it ignored the error argument in the callback, eventhough the callback might be called with one.
Allows resources to give back errors to the client when an invalid configuration happens.

### CODE REVIEW

**Comment by Maddis1337** [comment]
Why I think that this is a bug:
https://github.com/Maddis1337/deployd/blob/internal-resource-event-callback-fix/lib/resources/internal-resources.js#L281

**Comment by ericfong** [comment]
Thanks a lot
But, can you make the CI work too?

**Comment by Maddis1337** [comment]
@ericfong 
The error is not caused by my update. 
It is inside a node module and also you can take a look at my PR and how minor the changes are.

```
/home/travis/build/deployd/deployd/node_modules/doh/lib/handler.js:33
    res.on('close', function () {
        ^
TypeError: Object #<Object> has no method 'on'
    at Domain.<anonymous> (/home/travis/build/deployd/deployd/node_modules/doh/lib/handler.js:33:9)
    at Domain.emit (events.js:95:17)
    at process._fatalException (node.js:255:29)
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0

```

**Comment by andreialecu** [comment]
Can you explain exactly what kind of errors were hidden before this fix?

**Comment by Maddis1337** [comment]
Well over functions within deployd use the function with a error object,  see

https://github.com/Maddis1337/deployd/blob/internal-resource-event-callback-fix/lib/resources/internal-resources.js#L281

Other than that I used this in a plug-in I am working on

**Comment by NicolasRitouet** [comment]
I restarted travis ci build, the tests pass now.

**Comment by andreialecu** [comment]
The problem with exposing the actual error text is that something internal/sensitive may be disclosed to a potential attacker. I think we could opt for a more generic text like "Internal server error" instead.

This code is mainly used by the /dashboard however when saving configuration and deleting resources, so I'm not sure what types of errors could occur there.

Care to elaborate how this helps you exactly with your plugin?

**Comment by Maddis1337** [comment]
I develop an extended collection that allows to set indexes like unique to properties in a collection, but without this fix it is impossible to give the user feedback that the index could not get created if he changed the properties.

About the attacker issue: This fix only applies when the user is already authorized to update resources which means he has access to the dashboard.

**Comment by ericfong** [comment]
Do you want to have a PR for "set indexes like unique to properties" to the code of deployd? I think that will be great.

**Comment by Maddis1337** [comment]
Well, this has a pretty severe trade-off, which could be that it is possible that the adding an unique index will fail because the existing data breaks the constraint. This could massively impact existing deployd setups

**Comment by andreialecu** [comment]
@Maddis1337 can you add a unit test for this? It would make it more clear what it adds and it will make sure we won't break it further down the road. It should probably go in `resources.unit.js`.

**Comment by ipepe** [comment]
I support everything that will bring us unique indexing on properties!

**Comment by ericfong** [comment]
You may create another issue for that

**Comment by Maddis1337** [comment]
I finally found time to add unit tests.

**Comment by andreialecu** [comment]
I will have some time this week and will review/merge this then.

**Comment by andreialecu** [comment]
Thanks for your contribution!
Landed as https://github.com/deployd/deployd/commit/7cec886c7adde990b332f1c004d1b761e14d9274

**Pull request closed without merging**
