### PR TITLE
using require() without the command line

### PR DESCRIPTION
**Pull request by rgolea**
So I've been having this issue where I couldn't require modules from a project whenever I was running my own server. I added a couple of features where you can do `var module = require('name_of_the_module')` inside the app (basically I added dpd-event-extension to work natively with deployd) and I added an extra where you can do `var myCustomModule = requireLib('lib/test.js')` so you can add custom modules.

Hope you like it and if you have another thing in mind just feel free to reject this PR

### CODE REVIEW

**Comment by ericfong** [comment]
Is this related to #637 ?

**Comment by rgolea** [comment]
Have you used the #637 pr?

**Comment by ericfong** [comment]
Sorry, forget what is going on. Do we still need this ?

**Comment by rgolea** [comment]
I think not since you merged the other PR.

**Pull request closed without merging**
