### PR TITLE
feat(attach): add options for MongoClient

### PR DESCRIPTION
**Pull request by wtfil**
Extra configurations are required for some cloud-based providers

MongoClient did allow to accept extra options with seccond argument

```javasctipt
mongodb.MongoClient.connect(<connection string>, <options>, <callback>);
```

### CODE REVIEW

**Comment by andreialecu** [comment]
Thanks for your contribution!
Landed as https://github.com/deployd/deployd/commit/3a595b74869cfc2484003e937ab9218ace4688ae

**Comment by wtfil** [comment]
@andreialecu Hi! Thank you for merging!
Can you release new npm version?

**Comment by andreialecu** [comment]
@NicolasRitouet what do you think?

**Comment by NicolasRitouet** [comment]
I'll try to release later today

**Comment by wtfil** [comment]
Cool!

**Pull request merged**
