### PR TITLE
fix(user-collection): crash when password is not specified in login

### PR DESCRIPTION
**Pull request by andreialecu**
Added some further checks for returning an error when either the username or password is not specified on `login`.

### CODE REVIEW

**Comment by andreialecu** [comment]
Originally reported as #536

**Comment by Maddis1337** [comment]
I think you should keep/add my test cases: https://github.com/deployd/deployd/pull/539/files#diff-d2c37750d7b8fa629df78ceee2b16e6cR368

**Comment by andreialecu** [comment]
@Maddis1337 your PR is separate from this, mine is about `login`, yours is about creating users. Will merge yours separately.

**Comment by Maddis1337** [comment]
@andreialecu I deleted my comment, it was because you commented yesterday (which you later deleted). I will delete this comment later today, too.

**Comment by NicolasRitouet** [comment]
landed as 65f4170b7881ebb01ba50c4ee47fae22f3fe001e

Thanks @andreialecu  :+1:

**Pull request closed without merging**
