### PR TITLE
feature(collection): add AfterCommit event

### PR DESCRIPTION
**Pull request by andreialecu**
Added AfterCommit event that is executed after changes are committed to the database. The domain contains a `method` (POST/PUT/DELETE) property and allows access to the newly committed data using `this` or `data`.

Removed built in 'collectionname:changed' socket.io event on collection change.

You may now emit this manually from the AfterCommit event by simply running `emit('colname:changed')` from within it.

### CODE REVIEW

**Comment by andreialecu** [comment]
There's another use case for this event: 

I host my mongodb instance on heroku with a latency of ~100ms. When I emit change events from my On Post event for example - I have a listener that immediately issues a query for the changed data. But the changes haven't yet made it to the database, so the query returns nothing. 

This event ensures that whatever code is in AfterCommit only executed **after** the changes are confirmed in the database.

**Comment by ericfong** [comment]
Really Nice!

Another use case will be:
Trigger "User X have done Y event" emails/notification 

I am good with the "AfterCommit" event, but just want to know your point of view on
AfterPost, AfterPut, AfterDelete ?

**Comment by andreialecu** [comment]
AfterCommit is for all of that. You can do ` if (method === 'POST') { ... }` (or PUT or DELETE)

**Comment by NicolasRitouet** [comment]
I really like this PR!
Great job.

**Comment by ericfong** [comment]
Not sure why, got some error in SessionStore .getSession(uid) test

Error removing old sessions: MongoError: server localhost:27017 sockets closed

```
Unhandled rejection TypeError: Cannot call method 'remove' of undefined
    at /Users/eric/workspace/deployd/lib/db.js:484:9
    at /Users/eric/workspace/deployd/lib/db.js:155:12
    at tryCatcher (/Users/eric/workspace/deployd/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/eric/workspace/deployd/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/Users/eric/workspace/deployd/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/Users/eric/workspace/deployd/node_modules/bluebird/js/main/promise.js:646:14)
    at Promise.b (domain.js:183:18)
    at Async._drainQueue (/Users/eric/workspace/deployd/node_modules/bluebird/js/main/async.js:182:12)
    at Async._drainQueues (/Users/eric/workspace/deployd/node_modules/bluebird/js/main/async.js:187:10)
    at Async.drainQueues (/Users/eric/workspace/deployd/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickDomainCallback (node.js:492:13)
```

By

https://github.com/deployd/deployd/blob/master/lib/db.js#L155
[MongoError: server localhost:27017 sockets closed]

**Comment by AndreaPravato** [comment]
Very useful feature! Thanks and :thumbsup: to andreialecu and deployd

**Pull request closed without merging**
