### PR TITLE
Prevent server from crashing if username doesn't exist

### PR DESCRIPTION
**Pull request by rgolea**
I had some problems where if the user had been deleted and the session token was still sent, the server would crash. This fixes that problem.

### CODE REVIEW

**Comment by NicolasRitouet** [comment]
@rgolea thanks for your PR.
Could you add a test case with this?

**Comment by rgolea** [comment]
I will as soon as possible. I took some vacations.

**Comment by NicolasRitouet** [comment]
Enjoy then :sunny:

**Comment by docnoe** [comment]
I would prefer PR https://github.com/deployd/deployd/pull/647, which fixes the same problem, but in a much simpler way.

ref to #640

**Comment by NicolasRitouet** [comment]
#647 has been merged, it should solve the issue.

**Pull request closed without merging**
