### PR TITLE
fix(session): socket disconnection after login

### PR DESCRIPTION
**Pull request by xroussel**
Issue #533

### CODE REVIEW

**Comment by ericfong** [comment]
@andreialecu pls help to review this

**Comment by andreialecu** [comment]
Thanks for your contribution!
Landed as https://github.com/deployd/deployd/commit/56fe4d835d20026c1a46ae12a0a8f7e4f5562700

**Comment by andreialecu** [comment]
@xroussel If you can, please test #572. I have reworked how part of your PR works.

It solves some other problems, and I added some unit tests. But want to make sure there are no regressions.

**Comment by xroussel** [comment]
I tried with the last version, everything works fine for me.
Thanks !

**Pull request closed without merging**
