### PR TITLE
feature(collection): Add Collection.extendDomain()

### PR DESCRIPTION
**Pull request by andreialecu**
Static function that allows adding values or functions to the domains of all collection instances.

Replaces https://github.com/deployd/deployd/pull/315

### CODE REVIEW

**Comment by andreialecu** [comment]
You have access to `this.collection` and `this.domain` from inside any extensions defined using this method.

Usage example: 

app.js
```javascript
var Collection = require('deployd/lib/resources/collection');
var deployd = require('deployd');

Collection.extendDomain("getColName", function(){
  return this.collection.name;
});

Collection.extendDomain("hasChanges", function(){
  var domain = this.domain;
  if (_.find(_.keys(domain.data), function(key) {
    return domain.changed(key);
  })) {
    return true;
  }
  return false;
});

// configure database etc.
var server = deployd({
    port: process.env.PORT || 9000,
    env: process.env.ENV || 'development',
    db: {
        connectionString: process.env.MONGO_URI
    }
});

// start the server
server.listen();

// debug
server.on('listening', function () {
    console.log("Server is listening on port: " + (process.env.PORT || 9000));
});

// Deployd requires this
server.on('error', function (err) {
    console.error(err);
    process.nextTick(function () { // Give the server a chance to return an error
        process.exit();
    });
});
```

You can then use those defined functions in your event scripts, example:

On POST
```javascript
   emit(getColName() + ":post", this);
```

**Comment by ericfong** [comment]
WOW. Great Feature!!!

**Comment by andreialecu** [comment]
Yeah, it has a bit of dependency on #592. I can decouple if needed, but I also have another PR I need to send after these three which is related to AfterCommit as well.

So let's merge #592 first, that's easier.

**Comment by ericfong** [comment]
Thanks for your contribution!
Landed as 450b8adae23770ff7899fe8dceef971cdcb539c9

**Pull request closed without merging**
