### PR TITLE
fix(UserCollection): res.cookies not available from internal client

### PR DESCRIPTION
**Pull request by andreialecu**
Also improves a test that wasn't really testing anything prior to this. It now does proper assertions.

### CODE REVIEW

**Comment by NicolasRitouet** [comment]
Thx @andreialecu :+1:

**Comment by ipepe** [comment]
Thx, i will check it asap

**Comment by ericfong** [comment]
Thx

**Comment by ipepe** [comment]
I didn't respond, but I am now: 'It works'.

**Pull request merged**
