### PR TITLE
Added utf-8 encoding

### PR DESCRIPTION
**Pull request by GuilhermeMoreira**
Added utf-8 encoding to support pt-br and other languages accents on json response.

### CODE REVIEW

**Comment by rgolea** [comment]
Quite nice! Can you do it so you can extend that? Some people might need another charset

**Comment by NicolasRitouet** [comment]
We already had the exact same PR for that a few months ago:
https://github.com/deployd/deployd/pull/318

**Comment by GuilhermeMoreira** [comment]
Sorry I didn't see this other same PR.

Well, as pointed out then, I was having a problem with correctly displaying pt-br accents in the json response in Chrome, at least. Adding charset=utf-8 fixed it.

**Comment by rgolea** [comment]
@NicolasRitouet would an optional parameter be better?

**Comment by andreialecu** [comment]
This only seems to be an issue with the Chrome developer console. In actual XHR responses things come up fine. Probably a chrome bug: https://code.google.com/p/chromium/issues/detail?id=438464

**Comment by rgolea** [comment]
So, the reason I asked was that these are the unsupported languages for utf-8. Now I don't speak any of these languages but might it be useful to allow people to support these languages? Would be any problem in the current deployd structure? This is now just a curiosity and not really something related to this PR.
http://www.unicode.org/standard/unsupported.html

**Comment by juodumas** [comment]
JSON is always unicode, no need to add `charset=utf-8`. Moreover, JSON can be in `UTF-16` and `UTF-32`, not only in UTF-8: http://security.stackexchange.com/questions/82913/application-json-content-type-character-set. I believe this pull request can be closed.

As for unsupported languages, I think that unicode supports most and if there is a need, people using unsupported languages will go through the Unicode Consortium. The page you linked to states:
> Even though Unicode doesn't yet support these scripts, some of the languages which employ them are also commonly written with other scripts that are supported by Unicode.

**Comment by NicolasRitouet** [comment]
@juodumas thanks for your comment, I agree that we should close this PR.

**Pull request closed without merging**
